name: food_example
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  get: ^4.6.6
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  cloud_firestore: ^4.15.10
  logger: ^2.2.0
  cached_network_image: ^3.3.1
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  babstrap_settings_screen: ^0.1.6
  like_button: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  flutter_staggered_animations: ^1.1.1
  razorpay_flutter: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Biofit
  #     fonts:
  #       - asset: assets/fonts/Biotif-Regular.ttf
  #       - asset: assets/fonts/Biotif-Bold.ttf
  #         weight: 700
